### ISSUE TITLE
data and pretrained model

### ISSUE THREAD

**Issue by b0nz1** [avichaychriqui/HeBERT#1]
First i want to say that your work is great!!!

I have two questions:
1. When are you planning to publish your the model for Emotion Recognition?
2. Can you also publish the UGC annotated dataset (sentiment and emotion)?

**Comment by avichaychriqui** [comment]
Thank you so much for this comment! :) 

We are currently working on a paper that describes the model and the data. 
We will unfortunately be able to publish the ER model and the data only after the paper is published. 

We will keep you posted!
