### ISSUE TITLE
sentiment analysis -  getting LABEL_0,LABEL_1 instead of sentiments

### ISSUE THREAD

**Issue by katysei** [avichaychriqui/HeBERT#4]
I tried to use sentiment analysis using Hebert.
I keep getting LABEL_0 and LABEL_1 instead of sentiments.
also, LABEL_1 is always high no matter what the emotion.
best regards

**Comment by avichaychriqui** [comment]
Are you using the model that is at huggingface?
Try this link:
https://huggingface.co/avichr/heBERT_sentiment_analysis?text=I+like+you.+I+love+you
